import "./globals.css";
import type { Metadata } from "next";
import UserHeader from "@/components/Header";
import RecoilProvider from "@/components/RecoilProvider";
import { InitUser } from "@/components/InitUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RecoilProvider>
        <body>
          <InitUser />
          <UserHeader />
          {children}
        </body>
      </RecoilProvider>
    </html>
  );
}
